### ISSUE TITLE
fzaninotto/faker no soportada para php80

### ISSUE THREAD

**Issue by celli33** [phpcfdi/resources-sat-xml-generator#1]
A la hora de querer descargar el proyecto e instalarlo usando `composer install` en php80 obtenemos el error:
```
Problem 1
    - Root composer.json requires fzaninotto/faker ^1.9 -> satisfiable by fzaninotto/faker[v1.9.0, v1.9.1, v1.9.2].
    - fzaninotto/faker[v1.9.0, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
```
sugiero cambiar la librería al fork de: [fakerphp](https://github.com/FakerPHP).

**Comment by eclipxe13** [comment]
Fixed at 1d75311e4c2656a558304903ed64c53d2762b307
